### ISSUE TITLE
Change the Cabestan motor

### ISSUE THREAD

**Issue by alexmomo1212** [copl-labomc/fabconcept#12]
We need a new motor with lower torque and higher speed. Preferably, it should be from the same manufacturer so the size and shape is the same as the old one.

**Comment by cniallen** [comment]
As the purchase order form is getting re-formatted, let @joycopl and me know if you select the model to order before I publish the new form to use. We'll order for you with the temporary one if needed.

**Comment by joycopl** [comment]
The speed of the motor should be much higher than we have now. Check the similar motor with as much as possible higher speed. We will control the speed using potentiometer according to our requirements.

**Comment by alexmomo1212** [comment]
The new motor has arrived all we need is to change the motor holder (Issue #31)
