### ISSUE TITLE
Automate the spool

### ISSUE THREAD

**Issue by alexmomo1212** [copl-labomc/fabconcept#13]
Add a third motor and driver to automatically turn the spool. It has to pull the fiber at the same speed as the cabestan.

**Comment by cniallen** [comment]
I'm not sure if it's with @grudule and/or @JOGAU227 that we looked into the motors I got from Coractive... Did one of them could do the job to turn the spool?

Or with a large enough spool, would the current cabestan motor have enough speed?

**Comment by alexmomo1212** [comment]
Spool is automated
