### ISSUE TITLE
Fix the alignement of the diameter gauge

### ISSUE THREAD

**Issue by alexmomo1212** [copl-labomc/fabconcept#20]

**Comment by cniallen** [comment]
I was wondering if a spring loaded mechanism (bought from McMaster-Carr) wouldn’t be the best way to go… but than maybe less stable. Feel free to get advice from the mechanical workshop, their experience is much larger than all of ours combined on such things. I also wonder why Keyence didn’t provide some sort of fixation mechanism, you could write to them and ask if they have mounts already fitting the diameter gauge (not sure if it’s laser diodes or DELs btw) we could buy.

**Comment by grudule** [comment]
![image](https://github.com/copl-labomc/fabconcept/assets/46345094/927ee1ac-53a4-4e3c-ba16-b1d7a8615d72)
I designed and 3D printed 2 of this holder who used springloaded Thorlabs screws. One is already in place the second is in the workshop !
